<body>
<br>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <h1>Dashboard</h1>
                            <form method="post" class="nav flex-column">
                                <input class='nav-link' type="submit" name="button3" value="Items">
                            </form>
                        </li>
                        
                        <li class="nav-item">
                            <form method="post" class="nav flex-column">
                                <input class='nav-link' type="submit" name="button2" value="Categories">
                            </form>
                        </li>
                        
                        <li class='nav-item'>
                            <form method="post" class="nav flex-column">
                                <input class='nav-link' type="submit" name="button4" value="Add Item">
                            </form>
                        </li>
                        
                        <li class='nav-item'>
                            <form method="post" class="nav flex-column">
                                <input class='nav-link' type="submit" name="button5" value="Add Category">
                            </form>
                        </li>
              
                        <li class='nav-item'>
                            <form method="post" class="nav flex-column">
                                <input class='nav-link' type="submit" name="button1" value="Log out">
                            </form>
                        </li>
                    </ul>
                </div>
            </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                     
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <?php 
                    categoryOrItem();
                ?>
            </table>
        </div>
        <script>
            function confirmDelete(){
                return confirm("Do you want to delete this?");
            }
        </script>    
        </main>  
    </div>
</div>
