<main role="main">

  <!-- Title/subtitle and logo -->
  <div class="jumbotron">
    <div class="container" id="homeContainer">
      <br>
      <img src="img/brand.jpg" class="brand" alt="a1 watches logo">
      <br>
      <h6 id="welcomeStatement">We feature a variety of excellent time pieces at affordable prices and services for timely repairs!</h6>
      <br>
      <br>


      <!-- images of watches in positioning -->
      <div class="row">
        <div class="column">
          <img src="img/womens/bluejacqueline.jpg" id="watchImg" class="bluejacqueline" alt="blue watch">

        </div>
        <div class="column">
          <img src="img/mens/1orientbambino.jpg" id="watchImg" class="whiteorient" alt="white watch">

        </div>
        <div class="column">
          <img src="img/kids/batman.jpg" id="watchImg" class="timexgirls" alt="white purple watch">
        </div>
        <div class="column">
          <img src="img/mens/bluecasio.jpg" id="watchImg" class="bluecasio" alt="blue watch">
        </div>

        <div class="column">
          <img src="img/womens/virginiawhite.jpg" id="watchImg" class="virginiawhite" alt="whitewatch">


        </div>

      </div>


    </div>
  </div>

  <div class="container">

</main>

<hr>

</div> <!-- /container -->
<footer class="container">
  <p>&copy; Company 2017-2020</p>
</footer>