<div class="container-fluid">
    <div class="row">

        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Categories</span>
                    <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <form class="nav flex-column" action='?page=items' method='post'>
                    <?php postCategories('sideBar'); ?>
                </form>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Items</h1>
            </div>

            <h4><?php listCategoryDesc($categorySearch); ?></h4>

            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <?php
                    list_items($categorySearch);
                    ?>
                </table>
            </div>
        </main>

    </div>
</div>

<footer class="container">
    <p>&copy; Company 2017-2020</p>
</footer>