<main role="main"> ;
    <div class="jumbotron">
        <div class="container">

            <div id="main">
                <h1>Authorized Personnel Only</h1>
<!-- login form -->
                <form action="?page=dashboard" class="form-signin" method="POST">

                    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
                    <label for="inputEmail" class="sr-only">Email address</label>
                    <input type="text" id="inputEmail" name="username" class="form-control" placeholder="username=un" required autofocus>
                    <label for="inputPassword" class="sr-only">Password</label>
                    <input type="password" name="password" class="form-control" placeholder="password=pw" required>

                    <div class="checkbox mb-3">

                        <button class="btn btn-lg btn-primary btn-block" name="submit" type="submit" required>Sign in</button>
                </form>
            </div>
        </div>
    </div>
</div>

</main>

<hr>

<footer class="container">
        <p>&copy; Company 2017-2020</p>
    </footer>