<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <!-- search form -->
    <h1 class="searchbar">Search Bar</h1>
    <form class="example" action="/action_page.php">
      <input type="text" placeholder="Search.." name="search">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    </button>
  </div>
</div>
</div>
</div>

<div class="container">

  </main>


  <footer class="container">
    <p>&copy; Company 2017-2020</p>
  </footer>