<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Chi Calvin Nguyen, Simon Ung">

    <title>A1 Watches</title>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="img/favicon.png" rel=icon>

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/comp1230/assignments/assignment1/simon/public/index.php">A1 Watches</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item <?php echo is_active($page, 'home'); ?>">
                    <!-- function to show active page -->
                    <a class="nav-link" href="?page=home">Home </a>
                </li>
                <li class="nav-item <?php echo is_active($page, 'items'); ?>">
                    <a class="nav-link" href="?page=items">Items</a>
                </li>
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <form method="post" action="?page=items">
                            <?php postCategories('dropDown'); ?> <!-- function to show and operate dropdown -->
                        </form>
                    </div>
                </li>
                <li class="nav-item <?php echo is_active($page, 'search'); ?>">
                    <a class="nav-link" href="?page=search">Search</a>
                </li>
                <li class="nav-item <?php echo is_active($page, 'login'); ?>">
                    <a class="nav-link" href="?page=login">Admin Page</a>
                </li>


            </ul>

            <div>



            </div>
    </nav>
    <footer class="container">
        <p>&copy; Company 2017-2020</p>
    </footer>
    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>