-- MySQL Script generated by MySQL Workbench
-- Wed Dec  9 06:47:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assign2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `assign2` ;

-- -----------------------------------------------------
-- Schema assign2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assign2` DEFAULT CHARACTER SET utf8 ;
USE `assign2` ;

-- -----------------------------------------------------
-- Table `assign2`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assign2`.`category` ;

CREATE TABLE IF NOT EXISTS `assign2`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `status` ENUM('SHOW', 'HIDE') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign2`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assign2`.`items` ;

CREATE TABLE IF NOT EXISTS `assign2`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `brand` VARCHAR(45) NULL,
  `model` MEDIUMTEXT NULL,
  `diameter` VARCHAR(45) NULL,
  `price` DECIMAL(5,2) NULL,
  `status` ENUM('SHOW', 'HIDE') NOT NULL DEFAULT 'SHOW',
  PRIMARY KEY (`id`),
  INDEX `fk_items_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_items_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `assign2`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assign2`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assign2`.`members` ;

CREATE TABLE IF NOT EXISTS `assign2`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `memberscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `assign2`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `assign2`;
INSERT INTO `assign2`.`category` (`id`, `name`, `desc`, `status`) VALUES (1, 'Men\'s Watches', 'Watches For Men', 'SHOW');
INSERT INTO `assign2`.`category` (`id`, `name`, `desc`, `status`) VALUES (2, 'Women\'s Watches', 'Watches For Women', 'SHOW');
INSERT INTO `assign2`.`category` (`id`, `name`, `desc`, `status`) VALUES (3, 'Kid\'s Watches', 'Watches For Children', 'SHOW');

COMMIT;


-- -----------------------------------------------------
-- Data for table `assign2`.`items`
-- -----------------------------------------------------
START TRANSACTION;
USE `assign2`;
INSERT INTO `assign2`.`items` (`id`, `category_id`, `brand`, `model`, `diameter`, `price`, `status`) VALUES (1, 1, 'Casio', 'Men\'s Diver', '44mm', 84.99, DEFAULT);
INSERT INTO `assign2`.`items` (`id`, `category_id`, `brand`, `model`, `diameter`, `price`, `status`) VALUES (2, 2, 'Fossil', 'Women\'s Virginia', '30mm', 89.99, DEFAULT);
INSERT INTO `assign2`.`items` (`id`, `category_id`, `brand`, `model`, `diameter`, `price`, `status`) VALUES (3, 3, 'Pokemon', 'Kids\' Digital', '36mm', 9.99, DEFAULT);

COMMIT;

